info_file: data/info2.tsv

params:
    general:
        groups:
            group1: male
            group2: female
        min_depth:
            - 1
            - 2
            - 5
            - 10
    process:
        min-depth: 1

resources:
    process:
        threads: 4
        mem_mb: 20000
    general:
        mem_mb: 4000

default_settings_file: 'cfg/defaults.yaml'

ncbi:
    api_key: 9b747e0153782a735ef80e1ded2e7618be08
    email: romain.feron.91@gmail.com
    max_tries: 10
    sleep_between_tries: 1
