# General config file for the workflow.

# By default, the workflow is run for all datasets and figures.
# Edit this file to select specific datasets to run
info_file: data/info.tsv

# radsex parameters
params:
    general:  # These parameters will be used for all commands when applicable
        groups:
            group1: male
            group2: female
        min_depth:
            - 1
            - 2
            - 5
            - 10
    signif:
        output-fasta: true

resources:  # Define resources, mostly used when running on an HPC
    process:
        threads: 4
        mem_mb: 20000    # 20 Gb
        runtime_s: 7200  # 2 hours
    default:
        mem_mb: 4000     # 4 Gb
        runtime_s: 1800  # 30 minutes
    highmem:
        mem_mb: 12000    # 12 Gb
        runtime: 600     # 10 minutes

# This file contains default settings for all radsex commands.
# You should not have to edit that in theory.
default_settings_file: 'cfg/defaults.yaml'

# Config for NCBI queries; you can add your email and you api key if you have one
ncbi:
    api_key: 9b747e0153782a735ef80e1ded2e7618be08
    email: romain.feron.91@gmail.com
    max_tries: 10
    sleep_between_tries: 1
