# General config file for the workflow.

# By default, the workflow is run for all datasets and figures.
# Edit this file to select specific datasets to run
info_file: data/info.tsv

# radsex parameters
params:
    general:  # These parameters will be used for all commands when applicable
        groups:
            group1: male
            group2: female
        min_depth:
            - 1
            - 2
            - 5
            - 10
    process:
        min-depth: 1
    signif:
        output-fasta: true

resources:  # Define resources, mostly used when running on an HPC
    process:
        threads: 4
        mem_mb: 20000    # 20Gb
        runtime_s: 7200  # 2 hours
    default:
        mem_mb: 4000     # 4Gb
        runtime_s: 1800  # 30 minutes

# This file contains default settings for all radsex commands.
# You should not have to edit that in theory.
default_settings_file: 'cfg/defaults.yaml'

# Config for NCBI queries; you can add your email and you api key if you have one
ncbi:
    api_key: 
    email: xxx@yyy.com
    max_tries: 10
    sleep_between_tries: 1
