info_file: data/info.tsv

params:
    general:
        groups:
            group1: male
            group2: female
        min_depth:
            - 1
            - 2
            - 5
            - 10
    process:
        min-depth: 1

resources:
    process:
        threads: 4
        mem_mb: 20000
    general:
        mem_mb: 4000

default_settings_file: 'cfg/defaults.yaml'

ncbi:
    api_key:
    email:
    max_tries: 10
    sleep_between_tries: 1
