name: radsex-workflow
channels:
  - conda-forge
  - bioconda
dependencies:
  - radsex=1.1.2
  - r-sgtr=1.1.1
  - sra-tools=2.10.3
  - biopython=1.76
  - requests=2.23.0
  - xlwt=1.3.0 
  - xmltodict=0.12.0
